In [1]:
# import libraries
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt


In [56]:
# import data as dataframe and convert to numpy array
df = pd.read_csv('train.csv')
data = np.array(df)
m, n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n] / 255



In [53]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(0, Z)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A

def forward_propagation(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def deriv_ReLU(Z):
    return Z > 0

def back_propagation(Z1, A1, Z2, A2, W1, W2, X, Y):
    # m = Y.size
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * deriv_ReLU(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2


In [54]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, iterations, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_propagation(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_propagation(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print(f"Iteration: {i}")
            print(f"Accuracy: {get_accuracy(get_predictions(A2), Y)}")
    return W1, b1, W2, b2

In [57]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 100, 0.1)

Iteration: 0
[7 8 1 ... 8 1 8] [7 5 3 ... 1 5 6]
Accuracy: 0.0935609756097561
Iteration: 10
[7 8 1 ... 9 5 8] [7 5 3 ... 1 5 6]
Accuracy: 0.16519512195121952
Iteration: 20
[7 7 3 ... 9 5 8] [7 5 3 ... 1 5 6]
Accuracy: 0.23134146341463416
Iteration: 30
[7 7 3 ... 9 5 8] [7 5 3 ... 1 5 6]
Accuracy: 0.3067560975609756
Iteration: 40
[7 7 3 ... 9 5 7] [7 5 3 ... 1 5 6]
Accuracy: 0.38185365853658537
Iteration: 50
[7 7 3 ... 1 5 4] [7 5 3 ... 1 5 6]
Accuracy: 0.4383170731707317
Iteration: 60
[7 7 3 ... 1 5 4] [7 5 3 ... 1 5 6]
Accuracy: 0.485
Iteration: 70
[7 7 3 ... 1 5 4] [7 5 3 ... 1 5 6]
Accuracy: 0.5233414634146342
Iteration: 80
[7 7 3 ... 1 5 5] [7 5 3 ... 1 5 6]
Accuracy: 0.5560975609756098
Iteration: 90
[7 7 3 ... 1 5 5] [7 5 3 ... 1 5 6]
Accuracy: 0.5854878048780487
